### ISSUE TITLE
Broken property declaration prevents usage with PHP 8.2

### ISSUE THREAD

**Issue by titzel24** [udger/udger-php-v4#1]
Hello :wave: 

The declaration of property Parser::$data is broken:
https://github.com/udger/udger-php-v4/blob/df0768397a40dcf8883b097f3ea9630539d7552b/src/Parser.php#L35

Using PHP 8.2 this causes the following deprecation notice:
```
Creation of dynamic property Udger\Parser::$data is deprecated
```

**Comment by mallat** [comment]
Fixed, thanks for the heads up.
